### ISSUE TITLE
Stricting policies request body

### ISSUE THREAD

**Issue by vtdat** [vCloud-DFTBA/faythe#104]
Incorrect policies POST body cause system to not function

**Comment by ntk148v** [comment]
Because both policy's path and method contain a regex pattern, it's hard to validate them.

**Comment by vtdat** [comment]
> Because both policy's path and method contain a regex pattern, it's hard to validate them.

it can be validate in policy model? if no `path` and `method` key then returns error

**Comment by ntk148v** [comment]
> > Because both policy's path and method contain a regex pattern, it's hard to validate them.
> 
> it can be validate in policy model? if no `path` and `method` key then returns error
