### ISSUE TITLE
Sync between Prometheus Alertmanager's & Faythe's silences

### ISSUE THREAD

**Issue by ntk148v** [vCloud-DFTBA/faythe#34]
Prometheus Alertmanager and Faythe both have its own silences logic. User sometimes desires to create the same silence in both. Therefore, Faythe should have an option to allow keep sync with Prometheus Alertmanager's silences.

Not all sliences in Alertmanager be synced to Faythe, just the one with the special pattern in Comment.

**Comment by vtdat** [comment]
In case, user forgets to include that special pattern in the comment section, why don't we just sync all silences that only have instance in its matchers.

**Comment by ntk148v** [comment]
https://github.com/vCloud-DFTBA/faythe/pull/36
