### ISSUE TITLE
Clean up ETCD when 0 node in cluster

### ISSUE THREAD

**Issue by vtdat** [vCloud-DFTBA/faythe#37]
Should we clean up data of cluster after all nodes left to prevent mem leak?

**Comment by ntk148v** [comment]
No, we don't have to. Periodically, a node in cluster creates a request to keep its key alive. If it goes down for some reason, a key will be released. 

https://etcd.io/docs/v3.4.0/dev-guide/interacting_v3/#grant-leases

**Comment by vtdat** [comment]
Thanks
