### ISSUE TITLE
Cluster-bugs: Scalers are not distributed evenly

### ISSUE THREAD

**Issue by vtdat** [vCloud-DFTBA/faythe#39]
Steps to reproduce:
* Join 2 nodes to a cluster
* Create 2 scalers

Expected result:
* 1 scaler/node

Actual result:
* 2 scalers in 1 node

**Comment by ntk148v** [comment]
Use https://github.com/stathat/consistent/ to distribute key instead of https://github.com/ntk148v/hashring . It seems better :100:
