### ISSUE TITLE
Add list of ignore hosts for healing

### ISSUE THREAD

**Issue by vtdat** [vCloud-DFTBA/faythe#57]
Sometimes, hosts are under maintainance/development might be misevaluated as down and needed for healing.

Should have a method to avoid that case.

any thoughts @ntk148v?

**Comment by ntk148v** [comment]
* Create new key prefix, for example `/silences/<cloud/provider-id>`. Users creates a key `/silences/<cloud/provider-id>/<host-ip-address-to-exclude>` (A new API is required).  They can grant leases for keys from an etcd cluster. When a key is attached to a lease, its lifetime is bound to the lease’s lifetime which in turn is governed by a time-to-live (TTL). Each lease has a minimum time-to-live (TTL) value specified by the application at grant time.

https://etcd.io/docs/v3.4.0/dev-guide/interacting_v3/#grant-leases

* Without a lease, a exclude key stays until be deleted.
* Scalers/Healers watch the `/silences` prefix and update the exclude.
