### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by ntk148v** [vCloud-DFTBA/faythe#72]
We need a logo :call_me_hand:

**Comment by ntk148v** [comment]
![logo](https://user-images.githubusercontent.com/10803803/71496891-33ec2a00-2888-11ea-9747-61550da50bfe.png)

![logo](https://user-images.githubusercontent.com/10803803/71496902-3cdcfb80-2888-11ea-89ce-0508be67bab2.png)

![logo](https://user-images.githubusercontent.com/10803803/71496904-423a4600-2888-11ea-95c3-711aede8f18e.png)

**Comment by ntk148v** [comment]
![logo_transparent](https://user-images.githubusercontent.com/10803803/71497264-0f914d00-288a-11ea-9d8b-7edff5d60976.png)

![logo](https://user-images.githubusercontent.com/10803803/71497267-1324d400-288a-11ea-8ff4-89c808c6e363.png)

![logo](https://user-images.githubusercontent.com/10803803/71497272-17e98800-288a-11ea-8fe5-8b78b1f19e28.png)

**Comment by vtdat** [comment]
The transparent one looks good to me. Go for it.
