### ISSUE TITLE
etcd splits brain making faythe cannot connect to etcd cluster

### ISSUE THREAD

**Issue by vtdat** [vCloud-DFTBA/faythe#73]
in the case of 2 etcds, at 1 term when there is 1 rejection, etcd cluster cannot figure out which one is the leader. While our `watchChan` requires a leader https://github.com/vCloud-DFTBA/faythe/blob/d82e8ba93009fb7ed87863dd951321fe06abd3a7/pkg/common/etcd.go#L65, making faythe to hang and consume lots of CPU.

log etcd:

```log
{"log":"raft2019/12/29 19:14:37 INFO: 3956dc26679c1690 received MsgVoteResp rejection from ce02b42ac326e48b at term 36\n","stream":"stderr","time":"2019-12-29T19:14:37.509729738Z"}
{"log":"raft2019/12/29 19:14:37 INFO: 3956dc26679c1690 has received 1 MsgVoteResp votes and 1 vote rejections\n","stream":"stderr","time":"2019-12-29T19:14:37.50980695Z"}
```

log faythe:

```log
{"log":"level=error ts=2019-12-29T19:14:37.728Z caller=cluster.go:191 component=cluster msg=\"Error refreshing lease for cluster member\" err=\"context deadline exceeded\"\n","stream":"stderr","time":"2019-12-29T19:14:37.72894877Z"}
{"log":"level=error ts=2019-12-29T19:14:38.179Z caller=manager.go:198 component=\"healer manager\" msg=\"Error watching etcd cloud provider keys\" err=\"etcdserver: no leader\"\n","stream":"stderr","time":"2019-12-29T19:14:38.18010084Z"}
{"log":"level=error ts=2019-12-29T19:14:38.179Z caller=cluster.go:198 component=cluster msg=\"Error watching cluster state\" err=\"etcdserver: no leader\"\n","stream":"stderr","time":"2019-12-29T19:14:38.180206627Z"}
{"log":"level=error ts=2019-12-29T19:14:38.179Z caller=manager.go:235 component=\"healer manager\" msg=\"Error watching etcd healer keys\" err=\"etcdserver: no leader\"\n","stream":"stderr","time":"2019-12-29T19:14:38.180223212Z"}
{"log":"level=error ts=2019-12-29T19:14:38.179Z caller=manager.go:98 component=\"autoscale manager\" msg=\"Error watching etcd scaler keys\" err=\"etcdserver: no leader\"\n","stream":"stderr","time":"2019-12-29T19:14:38.180238145Z"}
```

pprof:

![profile001](https://user-images.githubusercontent.com/14995336/71607493-90af5380-2bac-11ea-8d5b-72a259cd7e7d.png)

**Comment by vtdat** [comment]
Not really a bug, but we should keep this in mind next time.

**Comment by vtdat** [comment]
Deploy 2n+1 etcd node and close this issue.

**Comment by ntk148v** [comment]
> Deploy 2n+1 etcd node and close this issue.

Refer link:

https://github.com/etcd-io/etcd/blob/master/Documentation/faq.md#why-an-odd-number-of-cluster-members

**Comment by ntk148v** [comment]
[ A 5-member etcd cluster can tolerate two member failures, which is enough in most cases.](https://github.com/etcd-io/etcd/blob/master/Documentation/faq.md#what-is-maximum-cluster-size)

**Comment by vtdat** [comment]
And we should have a retry scheme for increasing faythe fault tolerance.
