### ISSUE TITLE
Remove AT engine usage

### ISSUE THREAD

**Issue by ntk148v** [vCloud-DFTBA/faythe#85]
Currently we use AT engine - StackStorm as webhook and Mistral workflow store. May we can remove its usage by executing Mistral workflow directly?

**Comment by vtdat** [comment]
- Do we have a stable and production-ready Mistral client for Golang?
- Workflow executions and actions will be pulled to faythe-ui or should we accept that only admins of a cloud provider can see results?

**Comment by ntk148v** [comment]
>     * Do we have a stable and production-ready Mistral client for Golang?

* Gophercloud has one: https://github.com/gophercloud/gophercloud/blob/master/openstack/workflow/v2/workflows/doc.go . I haven't tested it yet and seems promising.

>     * Workflow executions and actions will be pulled to faythe-ui or should we accept that only admins of a cloud provider can see results?

* Bring these things to faythe-ui requires extra amount of works on faythe-ui. How about just put a executions link (or ID)? Users can check on OpenStack dashboard - Horizon. WDYT?

**Comment by vtdat** [comment]
> * Gophercloud has one: https://github.com/gophercloud/gophercloud/blob/master/openstack/workflow/v2/workflows/doc.go . I haven't tested it yet and seems promising.
- sure, should test it out first.

> * Bring these things to faythe-ui requires extra amount of works on faythe-ui. How about just put a executions link (or ID)? Users can check on OpenStack dashboard - Horizon. WDYT?

- IMO, users should know, at least, state of workflow before diving deeper into Horizon. Plus, if we have `gophercloud`, why don't we just take advantage of it
