### ISSUE TITLE
Cluster doesn't work as expected

### ISSUE THREAD

**Issue by ntk148v** [vCloud-DFTBA/faythe#88]
Faythe seems to have trouble with cluster mode if the number of members is more than 2.

**Comment by ntk148v** [comment]
We use KeepAliveOnce method to renew member lease. I suppose to change it to KeepAlive method for a better error handle. Also make changes of the Cluster struct.

**Comment by vtdat** [comment]
> We use KeepAliveOnce method to renew member lease. I suppose to change it to KeepAlive method for a better error handle. Also make changes of the Cluster struct.

let's try
